name: beta-to-tier4-main-sync

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: Source branch
        required: true
        type: string

jobs:
  sync-tier4-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Run sync-branches
        uses: autowarefoundation/autoware-github-actions/sync-branches@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base-branch: tier4/main
          sync-pr-branch: beta-to-tier4-main-sync
          sync-target-repository: https://github.com/tkimura4/autoware_launch.git
          sync-target-branch: ${{ inputs.target_branch }}
          pr-title: "chore: sync beta branch ${{ inputs.target_branch }} with tier4/main"
          pr-labels: |
            bot
            sync-tier4-upstream
          auto-merge-method: merge
